CREATE TABLE IF NOT EXISTS historial (id SERIAL PRIMARY KEY);
ALTER TABLE historial ADD COLUMN IF NOT EXISTS usuario_id INTEGER;
ALTER TABLE historial ADD COLUMN IF NOT EXISTS accion VARCHAR(200);
ALTER TABLE historial ADD COLUMN IF NOT EXISTS tabla_afectada VARCHAR(100);
ALTER TABLE historial ADD COLUMN IF NOT EXISTS registro_id INTEGER;
ALTER TABLE historial ADD COLUMN IF NOT EXISTS descripcion TEXT;
ALTER TABLE historial ADD COLUMN IF NOT EXISTS fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
UPDATE historial SET fecha=CURRENT_TIMESTAMP WHERE fecha IS NULL;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS estado_venezuela VARCHAR(80);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS codigo_cliente VARCHAR(50);
CREATE TABLE IF NOT EXISTS quejas (
  id SERIAL PRIMARY KEY,
  usuario_id INTEGER REFERENCES usuarios(id) ON DELETE SET NULL,
  asunto VARCHAR(200) NOT NULL,
  detalle TEXT NOT NULL,
  prioridad VARCHAR(30) NOT NULL DEFAULT 'normal',
  estado VARCHAR(30) NOT NULL DEFAULT 'pendiente',
  respuesta TEXT,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  respondido_en TIMESTAMP
);
